import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'

const projectRoot = process.cwd()
const outputRoot = path.join(projectRoot, 'public', '_generated', 'fonts')
const fontPackages = [
  { packageName: 'noto-serif-sc', label: 'Noto Serif SC Variable' },
  { packageName: 'noto-sans-sc', label: 'Noto Sans SC Variable' }
]

await rm(outputRoot, { recursive: true, force: true })
await mkdir(outputRoot, { recursive: true })

const cssParts = ['/* Generated by scripts/prepare-fonts.mjs. Do not edit directly. */']
let faceCount = 0

for (const font of fontPackages) {
  const packageRoot = path.join(projectRoot, 'node_modules', '@fontsource-variable', font.packageName)
  const sourceCss = await readFile(path.join(packageRoot, 'wght.css'), 'utf8')
  const outputFiles = path.join(outputRoot, font.packageName, 'files')
  await mkdir(path.dirname(outputFiles), { recursive: true })
  await cp(path.join(packageRoot, 'files'), outputFiles, { recursive: true })

  faceCount += (sourceCss.match(/@font-face/g) || []).length
  cssParts.push(
    `/* ${font.label} */`,
    sourceCss.replaceAll('./files/', `./${font.packageName}/files/`)
  )
}

await writeFile(path.join(outputRoot, 'fonts.css'), `${cssParts.join('\n\n')}\n`, 'utf8')
console.log(`延迟字体资源准备完成：${faceCount} 条 @font-face 声明`)
